server {
    server_name dev.ourglp1.com;

location / {
    proxy_pass https://localhost:5147;

    # Required for WebSocket support
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    # Standard headers
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}



    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/dev.ourglp1.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dev.ourglp1.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
