// src/pages/PrivacyPolicy.tsx
import { IonPage, IonContent } from '@ionic/react';
import React from 'react';
import styles from './PrivacyPolicy.module.css';
import { Browser } from '@capacitor/browser';

import TopNav from '@/context/TopNav';
import BottomNav from '@/context/BottomNav';

const link = (href: string, text: string) => (
  <a
    className={styles.link}
    href={href}
    onClick={async (e) => {
      e.preventDefault();
      await Browser.open({ url: href });
    }}
  >
    {text}
  </a>
);

const PrivacyPolicy: React.FC = () => {
  return (
   
    <IonPage>
      <TopNav showWhenAnon />

   
     <IonContent fullscreen className={styles.contentPad}>
     
        <div className={styles.container}>
          <h2 className={styles.title}>Privacy Policy — OurGLP1</h2>
          <p className={styles.updated}>Last updated: October 24, 2025</p>

          {/* Overview */}
          <section className={styles.card}>
            <h3 className={styles.sectionHeading}>Overview</h3>
            <p className={styles.body}>
              OurGLP1 helps you plan and track GLP-1 medication routines and personal wellness
              activities. We are committed to protecting your privacy and designed this app so
              your data stays on your device.
            </p>
          </section>

          {/* Data we store */}
          <section className={styles.card}>
            <h3 className={styles.sectionHeading}>Data Storage</h3>
            <p className={styles.body}>
              All information you enter in the app — such as your name, email, preferences, fasting
              or reminder data, weight logs, or medical plan — is stored locally on your device in
              a secure, sandboxed database. We do <strong>not</strong> operate a cloud backend or
              remote user database.
            </p>
          </section>

          <section className={styles.card}>
            <h3 className={styles.sectionHeading}>Apple Health Sync</h3>
            <p className={styles.body}>
              Apple Health sync is optional. If you grant permission, OurGLP1 can read supported
              health and activity data such as steps, active calories, exercise minutes, sleep,
              heart rate, and workouts. This may include data recorded by Apple Watch through Apple
              Health. Apple Health data is used to show your activity and wellness patterns inside
              the app and is stored locally on your device.
            </p>
          </section>

          <section className={styles.card}>
            <h3 className={styles.sectionHeading}>Coach and Third-party AI Services</h3>
            <p className={styles.body}>
              The in-app Coach uses built-in local guidance and saved app content. OurGLP1 does
              <strong> not</strong> send your name, email, profile, medication routine, health logs,
              Apple Health data, or Coach questions to OpenAI, ChatGPT, Anthropic, Gemini, or any
              other third-party AI service.
            </p>
          </section>

          {/* Data we collect automatically */}
          <section className={styles.card}>
            <h3 className={styles.sectionHeading}>Diagnostics & Analytics</h3>
            <p className={styles.body}>
              To help us improve app stability and usability, we may collect limited, anonymous
              diagnostic information such as:
            </p>
            <ul className={styles.list}>
              <li>App version, device model, and iOS version.</li>
              <li>Crash or error reports (via Sentry).</li>
              <li>Anonymous performance and feature usage statistics.</li>
            </ul>
            <p className={styles.body}>
              This data does not include your personal entries, health logs, or identifiable content.
              We use it solely for troubleshooting and product improvement.
            </p>
          </section>

          {/* Biometric Authentication */}
          <section className={styles.card}>
            <h3 className={styles.sectionHeading}>Biometric Authentication (Face ID / Touch ID)</h3>
            <p className={styles.body}>
              If you enable Face ID or Touch ID, authentication occurs entirely through your device’s
              Secure Enclave. OurGLP1 receives only a success/failure response — we never see or store
              biometric data.
            </p>
          </section>

          {/* Push Notifications */}
          <section className={styles.card}>
            <h3 className={styles.sectionHeading}>Notifications</h3>
            <p className={styles.body}>
              If you enable reminders or notifications, a secure push token is generated by Apple’s
              Push Notification service (APNs) to deliver those alerts. These tokens are anonymous and
              do not identify you personally. You can disable notifications at any time in iOS Settings.
            </p>
          </section>

          {/* How we use data */}
          <section className={styles.card}>
            <h3 className={styles.sectionHeading}>How We Use Data</h3>
            <ul className={styles.list}>
              <li>To operate the app (save and display your local entries).</li>
              <li>To display Apple Health activity and wellness data when you grant permission.</li>
              <li>To send push reminders and alerts you request.</li>
              <li>To improve reliability and performance through anonymized analytics.</li>
              <li>To communicate with you when you contact support.</li>
            </ul>
          </section>

          {/* Sharing */}
          <section className={styles.card}>
            <h3 className={styles.sectionHeading}>Sharing</h3>
            <ul className={styles.list}>
              <li>
                <strong>No Cloud Sync:</strong> Your personal data never leaves your device unless
                you export or share it yourself.
              </li>
              <li>
                <strong>Analytics Provider:</strong> We use Sentry for anonymous error and
                performance reporting under strict data-processing terms.
              </li>
              <li>
                <strong>No third-party AI sharing:</strong> Your personal data is not shared with
                third-party AI services.
              </li>
              <li>We do <strong>not</strong> sell, rent, or trade personal data.</li>
            </ul>
          </section>

          {/* Retention */}
          <section className={styles.card}>
            <h3 className={styles.sectionHeading}>Retention</h3>
            <p className={styles.body}>
              Because data lives on your device, you control how long it is retained. Deleting the
              app or clearing its data from your device removes your stored information permanently.
              Analytics logs (if any) are retained for limited periods (generally <strong>30–90 days</strong>)
              for technical analysis and automatically deleted afterward.
            </p>
          </section>

          {/* User control */}
          <section id="choices" className={styles.card}>
            <h3 className={styles.sectionHeading}>Your Choices & Controls</h3>
            <ul className={styles.list}>
              <li>Manage or delete your app data at any time from your device settings.</li>
              <li>Disable notifications in iOS Settings if you prefer not to receive reminders.</li>
              <li>
                Request support or deletion confirmation at{' '}
                {link('mailto:privacy@ourglp1.com', 'privacy@ourglp1.com')}.
              </li>
            </ul>
          </section>

          {/* Account Deletion */}
          <section className={styles.card}>
            <h3 className={styles.sectionHeading}>Account Deletion</h3>
            <p className={styles.body}>
              OurGLP1 does not maintain server accounts. Deleting the app or choosing “Delete Account”
              from your in-app settings removes your stored records immediately from your device.
            </p>
          </section>

          {/* Security */}
          <section className={styles.card}>
            <h3 className={styles.sectionHeading}>Security</h3>
            <p className={styles.body}>
              Your data never leaves your device without your action. Local data is stored in
              sandboxed app storage and protected by your device’s operating system encryption.
              When analytics or error data is transmitted, it is encrypted in transit using HTTPS.
            </p>
          </section>

          {/* Children */}
          <section className={styles.card}>
            <h3 className={styles.sectionHeading}>Children</h3>
            <p className={styles.body}>
              OurGLP1 is intended for adults. It is not directed to children under 13 (or the minimum
              age required in your region). We do not knowingly collect data from minors.
            </p>
          </section>

          {/* Contact */}
          <section className={styles.card}>
            <h3 className={styles.sectionHeading}>Contact</h3>
            <p className={styles.body}>
              General: {link('mailto:info@ourglp1.com', 'info@ourglp1.com')} · Privacy:{' '}
              {link('mailto:privacy@ourglp1.com', 'privacy@ourglp1.com')} · Support:{' '}
              {link('mailto:support@ourglp1.com', 'support@ourglp1.com')}
            </p>
          </section>

          <footer className={styles.footerNote}>
            <small className={styles.muted}>
              For billing or subscription assistance, contact{' '}
              {link('mailto:support@ourglp1.com', 'support@ourglp1.com')}.
            </small>
          </footer>
       
          
        </div>
      </IonContent>
     <BottomNav showWhenAnon />
    </IonPage>
  );
};

export default PrivacyPolicy;

