-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgsR6m1GAGSChqwJ0A
B+zJPsh1OMHWURQLqL5gSyyZI2qgCgYIKoZIzj0DAQehRANCAAQGNE4Wkq17ed4x
I5JCZbYdyWPtwnhq/SHRCLqU+5gPA2obYiqMOA4HANbj5DrJdDHcz9OfkRyS+Gvi
sn3e/yq7
-----END PRIVATE KEY-----